### ISSUE TITLE
代码不能运行

### ISSUE THREAD

**Issue by xiaoyong0312** [fanturbo/Weather#2]
我本地 android 环境都是好的，kotlin版本是1.1.50，代码下载到本地之后External Libraries 里面除了jdk其他的包都没有，因此代码也不能运行；

**Comment by fanturbo** [comment]
@xiaoyong0312 as版本多少？需要3.0

**Comment by xiaoyong0312** [comment]
android studio 最新版本 不是 2.3.3 嘛，我的就是最新的这个。

**Comment by fanturbo** [comment]
我创建项目是用的3.0预览版，好像某些插件是需要3.0版本的as的支持的。具体为什么我也没搞清楚，sorry

**Comment by xiaoyong0312** [comment]
没关系，只是找个kotlin 的简单项目看下。
